---
title: "Instacart Orders"
author: "Thalia Taffe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)

aisles <- read.csv("aisles.csv")
departments <- read.csv("departments.csv")
order_products <- read.csv("order_products__train.csv")
orders <- read.csv("orders.csv")
products <- read.csv("products.csv")
```

```{r, warning=FALSE}
orders <- orders %>% filter(eval_set == "train")

# merge aisles on products (aisle id) and departments on products (department id)
products <- inner_join(aisles, products, by = "aisle_id")
products <- inner_join(departments, products, by = "department_id")

# merge orders and order_products (on order id)
orders <- inner_join(orders, order_products, by = "order_id") %>%
  dplyr::select(!eval_set)

# merge both datasets ()
orders <- inner_join(orders, products, by = "product_id")
```

```{r}
orders <- orders %>% 
  filter(!department == "missing" & days_since_prior_order > 0)
```


```{r}
# select random subset of 2000 id
set.seed(542)

ids <- unique(orders$user_id) %>% sample(500)
orders <- orders %>% filter(user_id %in% ids)

sum(unique(orders$order_id))
sum(unique(orders$user_id))
orders
```



```{r}
orders %>% 
  group_by(user_id) %>% 
  ggplot(aes(x = days_since_prior_order)) + geom_histogram()
```


```{r}
orders %>% 
  #group_by(user_id) %>% 
  ggplot(aes(x = add_to_cart_order)) + geom_bar() + facet_wrap(~department)
```


```{r}
shopper_type <- function(df){
  convenience <- c("frozen", "bakery", "beverages", "babies", "pets", 
                 "snacks", "household", "personal care", "alcohol", "other")
  products <- df %>% group_by(user_id) %>% count()
  df$purpose <- "Unknown"
  c <- 0
  s <- 0
  
  x <- 1
  while (x <= length(df$department)){
    if (df$department[x] %in% convenience){
      c <- c + 1
      } else {
        s <- s + 1
    }
    if (c > s){
      df$purpose[x] <- "Convenience"
      } else {
        df$purpose[x] <- "Shopping"
      }
    x = x + 1
  }
  i <- 1
  while (i <= 500){
    if (products$n[i] <= 8){
      user <- products$user_id[i]
      df$purpose[df$user_id == user] <- "Convenience"
    }
    i <- i + 1
  }
  return(df)
}

orders <- shopper_type(orders)
```

```{r}
#ggplot(orders, aes(x = purpose, groupby = user_id)) + geom_bar()
q <- orders %>% group_by(order_id) %>% count()
o <- orders %>% group_by(user_id) %>% count() 
dim(o)[1]
dim(q)[1]
# same length = no repeat users

o %>% ggplot(aes(x = n)) + geom_histogram()
orders %>% dplyr::count(purpose)

```

```{r}
library(tidytext)

order_sub <- orders %>% 
  select(department, product_name) #%>% 
  #mutate(department_id = as.integer(department_id))

(order_tidy <- order_sub %>% unnest_tokens(word, product_name))

order_counts <- order_tidy %>% 
  group_by(word, department) %>%
  summarize(term_frequency = n(), .groups = "drop") %>%
  arrange(desc(term_frequency))

order_counts
```

```{r}
# ex. frozen food
library(ggwordcloud)

order_counts %>% 
  filter(department == "frozen") %>%
  slice_max(term_frequency, n = 50) %>%
  ggplot() +
  geom_text_wordcloud_area(aes(label = word, size = term_frequency)) +
  scale_size_area(max_size = 15)
```




